### ISSUE TITLE
Enum shape parity

### ISSUE THREAD

**Issue by petermikitsh** [strothj/babel-plugin-react-docgen-typescript#15]
When setting `{shouldExtractLiteralValuesFromEnum: true}`, this plugin outputs enums shaped like so:
```js
  Button.__docgenInfo = {
      "size": {
        "defaultValue": null,
        "description": "",
        "name": "size",
        "required": false,
        "type": {
          "name": "enum",
          "raw": "\"small\" | \"medium\" | \"large\"",
          "value": ["\"small\"", "\"medium\"", "\"large\""]
        }
  }
```

Other tools, such as [`react-docgen-typescript`](https://github.com/styleguidist/react-docgen-typescript/blob/a44eabe5bec0ab7ccbb65cd984056bee4b858955/src/parser.ts#L479), use a slightly different shape: values are an array of objects, with property `value`.

```js
  Button.__docgenInfo = {
        "size": {
            "defaultValue": null,
            "description": "",
            "name": "size",
            "required": false,
            "type": {
                "name": "enum",
                "value": [
                    {
                        "value": "\"small\""
                    },
                    {
                        "value": "\"medium\""
                    },
                    {
                        "value": "\"large\""
                    }
                ]
            }
        }
  }
```

This matters for upstream tools in storybook, like `storybook-addon-react-docgen` and `storybook-addon-smart-knobs`. The unexpected shape breaks props and knobs:

<img width="799" alt="Screen Shot 2020-03-23 at 7 02 24 PM" src="https://user-images.githubusercontent.com/1571918/77380663-ea9d6080-6d38-11ea-96e0-d0b9087c5511.png">

(Should be: `oneOf "small" | "medium" | "large"`)

Happy to PR this if maintainers agree with the change. Thanks!

**Comment by petermikitsh** [comment]
Here is the fix: https://github.com/petermikitsh/babel-plugin-react-docgen-typescript/commit/582cde2e30baf10788683b778cb8c485cf532e77.

**Comment by strothj** [comment]
Sure, feel free to submit this as a pull request.
