### ISSUE TITLE
TypeError: Property value expected type of string but got function

### ISSUE THREAD

**Issue by crimx** [strothj/babel-plugin-react-docgen-typescript#3]
Somehow this line of code throws the error. Haven't figured out what caused it.

https://github.com/strothj/babel-plugin-react-docgen-typescript/blob/9aeb278302c3de8bbb3b6d85ebf62b3b3da41722/src/index.ts#L127

**Comment by strothj** [comment]
Sorry for the late reply. I'd recommend using https://github.com/strothj/react-docgen-typescript-loader instead unless you have a need for this.

**Comment by crimx** [comment]
thanks. switched to the webpack loader and everything was fine again. didn't know that it can be used with babel typescript.

I'll leave the issue open and let you decide.
